### ISSUE TITLE
Relatório de Lucratividade por Venda

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft-lab/roadmap-erp#19]
Relatório não está somando a coluna custo.

**Comment by Parapinskijr** [comment]
[relatorio-de-lucratividade-venda.zip](https://github.com/udisoft-lab/roadmap-erp/files/3382256/relatorio-de-lucratividade-venda.zip)

**Comment by udisoft-lab** [comment]
Relatório migrado para a fábrica
