### ISSUE TITLE
Implementar módulo Inventário de Estoque - com possibilidade de leitura de código de barras

### ISSUE THREAD

**Issue by udisoft-lab** [udisoft-lab/roadmap-erp#6]
com as colunas (Descrição, Unidade, Custo Médio, Saldo Atual, Saldo Informado, Qtd Movimentada, Custo Total). Criar flag 
perguntando se zera o estoque para os itens não informados . *Movimentar DRE na rúbrica Variação de Estoque **Permitir 
edição das colunas Custo Médio e Saldo Informado ***Não permitir confirmar inventário sem custo médio.

**Comment by osmaroliveira** [comment]
Possibilidade de filtros para pesquisar os produtos, por exemplo por categoria, marca, fornecedor, depósito  - filtrar somente itens ativos.

**Comment by udisoft-lab** [comment]
Impressão de relatório ficará para o próximo release. Demanda #20
